---
version: '3'
services:
  db:
    container_name: geoarena_db
    image: kartoza/postgis:11.0-2.5
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DBNAME=geoarena
      - POSTGRES_PASS=geomaster
      - POSTGRES_USER=geomaster
      - ALLOW_IP_RANGE=0.0.0.0/0
      - TZ=Europe/Amsterdam
    volumes:
      -  dbdata:/var/lib/postgresql/data
    networks:
      - geo
  app:
    container_name: geoarena_app
    image: realulim/geoarena:latest
    ports:
      - 80:8090
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Europe/Amsterdam
    networks:
      - geo
    links:
      - db
    depends_on:
      - db
volumes:
  dbdata:
networks:
  geo:
